version: '3'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: films
      POSTGRES_USER: root
      POSTGRES_PASSWORD: s3cr3t
    ports:
      - '5432:5432'
